apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configs.k8.kubify.local
spec:
  version: v1
  group: k8.kubify.local
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: configs
    singular: config
    kind: Config
    shortNames:
    - cfg
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: environments.k8.kubify.local
spec:
  version: v1
  group: k8.kubify.local
  versions:
    - name: v1
      served: true
      storage: true
  scope: Cluster
  names:
    plural: environments
    singular: environment
    kind: Environment
    shortNames:
    - env